### ISSUE TITLE
ポート作成について（コンパイルは通るがrtcatで見えない）

### ISSUE THREAD

**Issue by rkoyama1623-jsk** [rkoyama1623/hrpsys-base#1]
## やりたいこと＝m_hogeInとm_hogeOutの追加

`m_hogeIn`と`m_hogeOut`というポートを作ろうとしています。
(`m_sbpCogOffsetOut("sbpCogOffset", m_sbpCogOffset)`というコードが`Autobalancer.cpp`にあったので、sbpもすでにoutはしている？かもしれないということでとりあえず、ポートの勉強用。
https://github.com/fkanehiro/hrpsys-base/pull/743/files
を参考にしています。)
https://github.com/fkanehiro/hrpsys-base/compare/master...rkoyama1623:study-autobalancer
のように、ポートの追加とm_hogeOutのポートからへのwriteをしてみましたが、rtcatしてもポートが見えないです。

考えられる理由としては、
- データのながれがないポートは見えない？→と思ってwrite()する行を追加しましたが、改善せず。[ここ](https://github.com/fkanehiro/hrpsys-base/compare/master...rkoyama1623:study-autobalancer#diff-eb446f98e459d63000964d63fc0a3365R590)
- ポートをつながないと、ポートは見えない？
## 行ったこと

```
git remote add koyama http://github.com/rkoyama1623/hrpsys-base                 
git fech koyama                                                                 
git checkout -b study-autobalancer koyama/study-autobalancer                    
catkin bt                                                                       
```

でhrpsys-baseを更新し、hcfからｒｔｃを起動。

```
ipython -i ~/ros/hydro_parent/src/hrpsys/sample/SampleRobot/samplerobot_data_logger.py -i
```

そして、ポートの確認

```
rtcat localhost:15005/abc.rtc

abc.rtc  Active
  Category       example
  Description    autobalancer component
  Instance name  abc
  Type name      AutoBalancer
  Vendor         AIST
  Version        315.7.0
  Parent         
  Type           Monolithic
 +Extra properties
+Execution Context 0
+DataInPort: qRef
+DataInPort: basePosIn
+DataInPort: baseRpyIn
+DataInPort: zmpIn
+DataInPort: optionalData
+DataInPort: emergencySignal
+DataOutPort: q
+DataOutPort: zmpOut
+DataOutPort: basePosOut
+DataOutPort: baseRpyOut
+DataOutPort: baseTformOut
+DataOutPort: basePoseOut
+DataOutPort: accRef
+DataOutPort: contactStates
+DataOutPort: controlSwingSupportTime
+DataOutPort: cogOut
+CorbaPort: AutoBalancerService
+DataInPort: ref_lfsensor
+DataInPort: ref_rfsensor
+DataInPort: ref_lhsensor
+DataInPort: ref_rhsensor
+DataOutPort: limbCOPOffset_lfsensor
+DataOutPort: limbCOPOffset_rfsensor
+DataOutPort: limbCOPOffset_lhsensor
+DataOutPort: limbCOPOffset_rhsensor
```

hogeを含むポートはない・・・
何かアドバイスお願いします。

@mmurookaさん
@YutaKojio

**Comment by rkoyama1623-jsk** [comment]
書き忘れましたが、コンパイルは通ります。

**Comment by mmurooka** [comment]
>    データのながれがないポートは見えない？→と思ってwrite()する行を追加しましたが、改善せず。ここ
>     ポートをつながないと、ポートは見えない？

については，
データが流れていなくても，また，ポートがつながっていなくても，rtcatで見えます．

**Comment by rkoyama1623-jsk** [comment]
ということは、コードに不備があるだけですね。
もう一度よく見てみます。

**Comment by mmurooka** [comment]
> hcfからｒｔｃを起動。

は，どういう意味かな．
まずhrpsysは起動して，それからhcfを起動するという順番です．
hrpsysは起動してる？
rtmlaunch hrpsys_ros_bridge samplerobot.launch
や
rtmlaunch hrpsys samplerobot.launch
で起動できます．

**Comment by mmurooka** [comment]
あと，
sbp_offsetはabcの中で使って，それより後のrtcでは使わないと思うので，
outポートはいらない気がしています．

**Comment by mmurooka** [comment]
koyamaブランチで試したら，hogeのポート見えました．
そのままで何も書き換えていないです．

https://github.com/rkoyama1623/hrpsys-base/blob/cb66b3171ba6194e0f615ddc68e365b111f4dd3c/rtc/AutoBalancer/AutoBalancer.cpp#L591
のhogeもたくさん出力されています．
小山が試しているときは，このhogeの出力はでますか？
これが出ていないなら，
新しいソースをコンパイルできていないか，これを使えていないのだと思います．

```
leus@cygnus:~/ros/hydro_parent/src/hrpsys/rtc/AutoBalancer$ rtcat localhost:15005/abc.rtc
abc.rtc  Active
  Category       example
  Description    autobalancer component
  Instance name  abc
  Type name      AutoBalancer
  Vendor         AIST
  Version        315.7.0
  Parent         
  Type           Monolithic
 +Extra properties
+Execution Context 0
+DataInPort: qRef
+DataInPort: basePosIn
+DataInPort: baseRpyIn
+DataInPort: zmpIn
+DataInPort: optionalData
+DataInPort: emergencySignal
+DataInPort: hogeIn
+DataOutPort: q
+DataOutPort: zmpOut
+DataOutPort: basePosOut
+DataOutPort: baseRpyOut
+DataOutPort: baseTformOut
+DataOutPort: basePoseOut
+DataOutPort: accRef
+DataOutPort: contactStates
+DataOutPort: controlSwingSupportTime
+DataOutPort: cogOut
+DataOutPort: walkingStates
+DataOutPort: sbpCogOffset
+DataOutPort: hogeOut
+CorbaPort: AutoBalancerService
+DataInPort: ref_lfsensor
+DataInPort: ref_rfsensor
+DataInPort: ref_lhsensor
+DataInPort: ref_rhsensor
+DataOutPort: lfsensor
+DataOutPort: rfsensor
+DataOutPort: lhsensor
+DataOutPort: rhsensor
+DataOutPort: limbCOPOffset_lfsensor
+DataOutPort: limbCOPOffset_rfsensor
+DataOutPort: limbCOPOffset_lhsensor
+DataOutPort: limbCOPOffset_rhsensor
```

**Comment by YutaKojio** [comment]
ちなみにぼくの環境でも同じようにhogeのポートも出ています．

**Comment by mmurooka** [comment]
https://github.com/rkoyama1623/hrpsys-base/issues/1#issuecomment-169653972
のコメントで修正ですが，

```
 rtmlaunch hrpsys_ros_bridge samplerobot.launch
```

は，stableなrtcだけが起動して，abc,st,icなどのunstableなrtcは起動しないので，
今回の確認には使えませんでした．
（unstableというのは別に不安定なわけではなくて，そういう名前の分類になっているだけ）

```
rtmlaunch hrpsys samplerobot.launch
ipython -i ~/ros/hydro_parent/src/hrpsys/sample/SampleRobot/samplerobot_data_logger.py -i
```

や

```
rtmlaunch hrpsys_ros_bridge samplerobot.launch USE_UNSTABLE_RTC:=true
```

や

```
 rtmlaunch hrpsys_ros_bridge_tutorials samplerobot.launch
```

なら，unstableなrtcも起動します．

**Comment by rkoyama1623-jsk** [comment]
返信ありがとうございます。

> hcfからｒｔｃを起動。
> は，どういう意味かな．
> まずhrpsysは起動して，それからhcfを起動するという順番です．
> hrpsysは起動してる？

rtmlaunchが抜けていましたが、

```
rtmlaunch hrpsys samplerobot.launch
ipython -i ~/ros/indigo_parent/src/hrpsys/sample/SampleRobot/samplerobot_data_logger.py -i
```

を行っていました。

よくみると、私のhrpsysでは、sbpCogOffsetのポートも見えていないです。
また、hogeの出力もない。
indigo環境を利用しているのですが、それが関係あるでしょうか？
buildの仕方は、ros/insigo_parent/src/hrpsys/で

```
catkin build --this --force-cmake
```

であっていますか？

**Comment by YutaKojio** [comment]
> buildの仕方は、ros/insigo_parent/hrpsys/で

タイポかもしれませんが，
`roscd hrpsys`
で　~/ros/indigo_parent/devel/share/hrpsys に移動
`catkin bt`
です．

**Comment by rkoyama1623-jsk** [comment]
develでbuildするのですか！
srcだと思っていました。それが原因のようです。
試してみます。ありがとうございます。

**Comment by mmurooka** [comment]
develでするんだっけ？
僕はいつも ~/ros/hydro_parent/src/hrpsys で
`catkin bt --force-cmake` しています．
今回もそうしていました．

**Comment by rkoyama1623-jsk** [comment]
roscdで気づいたのですが、hrpsysがdebで入っていました。
これが原因のようです。
たぶんchoreonoid関連のパッケージを入れるときに、rosdepで誤って入ってしまったようです。

**Comment by YutaKojio** [comment]
> develでbuildするのですか！
> srcだと思っていました。それが原因のようです。

たぶんこれはどっちでもいいです．

**Comment by rkoyama1623-jsk** [comment]
debのhrpsysを削除したらhogehogeが出て来ました。
皆様、誠にありがとうございました。
